DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Lost;
DROP TABLE IF EXISTS Found;
DROP TABLE IF EXISTS Sheltered;
DROP TABLE IF EXISTS Sighting;
DROP TABLE IF EXISTS Reward;
DROP TABLE IF EXISTS Vet;
DROP TABLE IF EXISTS Operation;
DROP TABLE IF EXISTS Adoption;
DROP TABLE IF EXISTS Shelter;
DROP TABLE IF EXISTS Campus;


CREATE TABLE Users(
    userid SERIAL,
	username VARCHAR(32) UNIQUE NOT NULL,
	password TEXT NOT NULL,
	isActive BOOLEAN NOT NULL DEFAULT TRUE,
	PRIMARY KEY (userid)
);


INSERT INTO Users (USERNAME, PASSWORD) VALUES ('hey', 'yo');
INSERT INTO Users (USERNAME, PASSWORD) VALUES ('adafafa', 'dafafaf');

CREATE TABLE Pet
(
pid CHAR(16),
uid CHAR(16),
name CHAR(10),
sex CHAR(1),
birthDate DATE,
regDate DATE,
breed CHAR(20),
imageURL CHAR(100),
PRIMARY KEY (pid)
FOREIGN KEY(uid) REFERENCES User
ON DELETE NO ACTION
);


CREATE TABLE Lost
(
pid CHAR(16),
lostDate CHAR(6),
lostTime CHAR(6),
lostLat FLOAT,
lostLong FLOAT,
PRIMARY KEY (pid),
FOREIGN KEY (pid) REFERENCES Pet
);
